version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: monitoring-redis
    restart: always
    ports:
      - "7963:6379"
    volumes:
      - monitoring-redis:/data
    networks:
      - monitoring-network
    # environment:
    #   - REDIS_PASSWORD=12420213
    # command: ["redis-server", "--requirepass", "12420213"]

  mongo:
    image: mongo:latest
    container_name: monitoring-mongo
    restart: always
    ports:
      - "17027:27017"
    volumes:
      - monitoring-mongo:/data/db
    networks:
      - monitoring-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12420213

  influx:
    image: influxdb:latest
    container_name: monitoring-influx
    restart: always
    ports:
      - "8680:8086"
    volumes:
      - monitoring-influx-data:/var/lib/influxdb2
      - monitoring-influx-config:/etc/influxdb2
    networks:
      - monitoring-network
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=amir
      - DOCKER_INFLUXDB_INIT_PASSWORD=amir200300
      - DOCKER_INFLUXDB_INIT_ORG=BlackIQ
      - DOCKER_INFLUXDB_INIT_BUCKET=monitoring
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=this-is-a-fucking-super-adv-secret-token-bitch

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitoring-app
    restart: always
    ports:
      - "9999:8000"
    networks:
      - monitoring-network
    depends_on:
      - redis
      - mongo
      - influx
    env_file:
      - .env.local

volumes:
  monitoring-redis:
    external: true
  monitoring-mongo:
    external: true
  monitoring-influx-config:
    external: true
  monitoring-influx-data:
    external: true

networks:
  monitoring-network:
    external: true
