version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: amir-monitoring-redis
    ports:
      - "7963:6379"
    volumes:
      - /Users/amirhosseinmohammadi/Projects/amirhossein/amir-monitoring/data/redis:/data
    environment:
      - REDIS_PASSWORD=12420213
    command: ["redis-server", "--requirepass", "12420213"]

  mongo:
    image: mongo:latest
    container_name: amir-monitoring-mongo
    ports:
      - "17027:27017"
    volumes:
      - /Users/amirhosseinmohammadi/Projects/amirhossein/amir-monitoring/data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12420213
