"""Check for any update

Revision ID: 2e285ff9520f
Revises: a9b3a7ae95b5
Create Date: 2026-07-21 23:26:03.735671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e285ff9520f'
down_revision: Union[str, Sequence[str], None] = 'a9b3a7ae95b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('pages', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('pages', 'name')
    # ### end Alembic commands ###
