"""complete_relations

Revision ID: 977fb1cc4533
Revises: b1c5f21827b7
Create Date: 2026-07-30 19:18:09.133109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '977fb1cc4533'
down_revision: Union[str, Sequence[str], None] = 'b1c5f21827b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_tags',
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('host_id', 'tag_id')
    )
    op.add_column('hosts', sa.Column('group_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_hosts_group_id'), 'hosts', ['group_id'], unique=False)
    op.create_foreign_key(None, 'hosts', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hosts', type_='foreignkey')
    op.drop_index(op.f('ix_hosts_group_id'), table_name='hosts')
    op.drop_column('hosts', 'group_id')
    op.drop_table('host_tags')
    # ### end Alembic commands ###
