"""Typos

Revision ID: a9b3a7ae95b5
Revises: 25438be17ca9
Create Date: 2026-07-21 19:55:13.975690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b3a7ae95b5'
down_revision: Union[str, Sequence[str], None] = '25438be17ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('port', sa.Integer(), nullable=False))
    op.add_column('hosts', sa.Column('api_key', sa.String(), nullable=False))
    op.add_column('hosts', sa.Column('agent_availability', sa.Boolean(), nullable=False))
    op.alter_column('hosts', 'ipv4',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hosts', 'ipv6',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hosts', 'dns',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('hosts', 'post')
    op.drop_column('hosts', 'apikey')
    op.drop_column('hosts', 'agent_availablity')
    op.add_column('pages', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('pages', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('pages', 'title')
    op.add_column('hosts', sa.Column('agent_availablity', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('hosts', sa.Column('apikey', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('hosts', sa.Column('post', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('hosts', 'dns',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('hosts', 'ipv6',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('hosts', 'ipv4',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('hosts', 'agent_availability')
    op.drop_column('hosts', 'api_key')
    op.drop_column('hosts', 'port')
    # ### end Alembic commands ###
