"""Remove IPv6 column

Revision ID: d34c8ef1bd8f
Revises: 2e285ff9520f
Create Date: 2026-07-25 16:19:41.446398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34c8ef1bd8f'
down_revision: Union[str, Sequence[str], None] = '2e285ff9520f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'ipv6')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('ipv6', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
